on: issue_comment
name: Issue Comments
permissions:
  issues: write
jobs:
  check_comments:
    name: Check comments for /deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check for Command
        id: command
        uses: xt0rted/slash-command-action@v1
        with:
          command: deploy
          reaction: "true"
          reaction-type: "eyes"
          allow-edits: "false"
          permission-level: admin
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy
        # Only run this step if the branch is main
        if: ${{ (github.ref == 'refs/heads/main') || (github.ref == 'refs/heads/develop') }}
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
         echo "Deploying last changes on env:pre-production platform:render"
         curl "$deploy_url"
