name: Auto message for PR's and Issues
on: [pull_request, issues]
jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - name: Start Job
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hey, thank you for opening this Issue ! 🙂"
          pr-message: "Hey, thank you for opening this Pull Request !"
